/**
 * Stable, machine-readable error codes. The frontend maps these to
 * user-friendly copy, so never repurpose an existing code.
 */
export const ERROR_CODES = Object.freeze({
  // Generic
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  RATE_LIMITED: 'RATE_LIMITED',
  BAD_REQUEST: 'BAD_REQUEST',

  // Auth
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  USERNAME_TAKEN: 'USERNAME_TAKEN',

  // Channels
  CHANNEL_NOT_FOUND: 'CHANNEL_NOT_FOUND',
  CHANNEL_NAME_TAKEN: 'CHANNEL_NAME_TAKEN',
  CHANNEL_EXPIRED: 'CHANNEL_EXPIRED',
  CHANNEL_PASSWORD_REQUIRED: 'CHANNEL_PASSWORD_REQUIRED',
  CHANNEL_PASSWORD_INVALID: 'CHANNEL_PASSWORD_INVALID',
  CHANNEL_NOT_JOINED: 'CHANNEL_NOT_JOINED',
  CHANNEL_LIMIT_REACHED: 'CHANNEL_LIMIT_REACHED',
  CHANNEL_OWNER_CANNOT_LEAVE: 'CHANNEL_OWNER_CANNOT_LEAVE',

  // Messages
  MESSAGE_TYPE_UNSUPPORTED: 'MESSAGE_TYPE_UNSUPPORTED',

  // Attachments
  ATTACHMENT_NOT_FOUND: 'ATTACHMENT_NOT_FOUND',
  ATTACHMENT_TOO_LARGE: 'ATTACHMENT_TOO_LARGE',
  ATTACHMENT_TYPE_UNSUPPORTED: 'ATTACHMENT_TYPE_UNSUPPORTED',
  ATTACHMENT_CONTENT_MISMATCH: 'ATTACHMENT_CONTENT_MISMATCH',
  ATTACHMENT_LIMIT_REACHED: 'ATTACHMENT_LIMIT_REACHED',
  ATTACHMENT_ALREADY_USED: 'ATTACHMENT_ALREADY_USED',
  UPLOAD_FAILED: 'UPLOAD_FAILED',

  // WebSocket
  WS_UNKNOWN_EVENT: 'WS_UNKNOWN_EVENT',
  WS_MALFORMED_FRAME: 'WS_MALFORMED_FRAME',
  WS_NOT_AUTHENTICATED: 'WS_NOT_AUTHENTICATED',
});
